[project]
name = "meu-servidor-fastmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "fastmcp>=3.4.5",
    "google-genai>=2.16.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.52.1",
]

[project.scripts]
fastmcp = "fastmcp:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
